version: "3.7"

services:
  coming_soon_app:
    container_name: coming_soon_app
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "8088:80"